import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from "@/components/nav/nav";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { UserProvider } from "@/context/user/userContext";
import { SelectionProvider } from "@/context/selection/selectionContext";
import { ResultProvider } from "@/context/result/resultContext";
import ResultPopup from "@/components/result/restultPopup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <UserProvider>
            <SelectionProvider>
              <ResultProvider>
                <Nav />
                <ResultPopup />
                {children}
              </ResultProvider>
            </SelectionProvider>
          </UserProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
